---
#
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2020 The Authors.
# Authors: Bin Liang  <@liangbin>
#
# Summary: Group specific playbook variables for Inventory group named "aws"
#
ansible_port: 22
ansible_user: "ubuntu"
ansible_ssh_user: "ubuntu"
ansible_ssh_private_key_file: "~/.ssh/Bin-ssh-keypair-testVM.pem"
