---
#
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2020-2022 The Authors.
# Authors:     Bin Liang     <@liangbin>
# Modified by: Wei Yue       <@w-yue>
#
# Summary: Play to deploy Arion services on target k8s cluster
#
## ============== Play to deploy arion services to target cluster ================================
- name: "==== Deploy Arion management services"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Deploy arion-operator service"
      shell: "../install/deploy_mgmt.sh &>>{{DBG_LOG}}"
      args: 
        executable: /bin/bash
      environment:
        STAGE: "{{stage}}"
        REG: "{{reg}}"
      register: "output"
    - debug: var=output.stdout_lines

    - name: "Deploy arion-manager service"
      shell: "../install/deploy_arion_manager.sh &>>{{DBG_LOG}}"
      args: 
        executable: /bin/bash
      environment:
        STAGE: "{{stage}}"
        REG: "{{reg}}"
        K8S_TYPE: "{{k8s_type}}"
      register: "output"
    - debug: var=output.stdout_lines

    - name: "Check Arion Control Plane deployment completion"
      shell: "../install/deploy_wellcheck.sh"
      args: 
        executable: /bin/bash
      environment:
        K8S_TYPE: "{{k8s_type}}"
      register: "output"
    - debug: var=output.stdout_lines

- name: "==== provision Arion Gateway Cluster"
  hosts: zgc
  vars:
    local_user: "{{ansible_user}}"
  gather_facts: false
  tasks:
    - include: tasks/zgc-node.yml
      when: site != "kind"

    - name: "KIND ZGC deployment"
      shell: "../kind/create_zgc.sh {{stage}} {{droplet_size}} &>> {{DBG_LOG}}"
      args: 
        executable: /bin/bash
      environment:
        STAGE: "{{stage}}"
        REG: "{{reg}}"
      register: "output"
      when: site == "kind"
    - debug: var=output.stdout_lines
      when: site == "kind"
